### PR TITLE
Revert "Testdata creation"

### PR DESCRIPTION
**Pull request by kyle-messier**
Reverts NIEHS/beethoven#290

### CODE REVIEW

**Comment by kyle-messier** [comment]
@eva0marques The merging of the test dataset creation has caused errors in test-coverage and R-CMD-check. Can you check the 3 failed tests? I tried reverting, but not working. @sigmafelix also if want to resolve. Thanks!

**Comment by sigmafelix** [comment]
@kyle-messier @eva0marques I will investigate the issue.

**Comment by eva0marques** [comment]
I do not remember why this pull request was not closed but it sounds that some tests about cross validation are no longer valid. I guess it is because @insang you improved the code in that script and merge to main branch? Maybe we can just remove this cross validation file from my pull request? Sorry about that.

**Comment by sigmafelix** [comment]
@eva0marques I checked out this branch and all tests in the problem passed in my end. I cleared GitHub Action cache and am rerunning the tests now.

**Comment by eva0marques** [comment]
Nice, thanks.

**Comment by eva0marques** [comment]
@sigmafelix I'm updating test-temporal-range, that might be the problem...

**Comment by sigmafelix** [comment]
@eva0marques I couldn't figure out what the problem exactly is. I changed the global set.seed part into withr::local_seed in this trial. Let's see what happens.

**Comment by eva0marques** [comment]
I hope that merging this branch into main won't remove work done on main branch since then.

**Comment by eva0marques** [comment]
I just realized that this pull request erased my script [create_testdata.R](https://github.com/NIEHS/beethoven/blob/main/tests/testdata/create_testdata.R) for test data creation.

**Comment by kyle-messier** [comment]
@eva0marques @sigmafelix R CMD and test-coverage are both failing beacuse of 3 failed tests:

══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-cross_validation.R:61:3'): leave-ones run without errors ─────
max(index_loto) not equal to `tlength`.
1/1 mismatches
[1] NA - 10 == NA
── Failure ('test-temporal_range.R:17:3'): covariates are within temporal range. ──
all(iswithin) not equal to TRUE.
1 element mismatch
── Failure ('test-temporal_range.R:27:3'): test_nc_output.nc is within temporal range. ──
all(iswithin) not equal to TRUE.
1 element mismatch

**Comment by eva0marques** [comment]
@kyle-messier we see that but we don't understand why.

**Review by eva0marques — APPROVED** [review]
I trust you @sigmafelix lol

**Pull request merged**
