### PR TITLE
Create aqs with siteid

### PR DESCRIPTION
**Pull request by eva0marques**
I show to Anisha how to do a pull request. We just called amadeus function to create a rds file in output/ with site_id, time, lat, lon, geometry. It's our first step to create spatio-temporal cross validation indexes.

### CODE REVIEW

**Comment by kyle-messier** [comment]
@eva0marques @Sanisha003 Ok- that is fine as we are still going with /output. Soon that will be replaced by targets, but we'll handle that when the time comes. Thanks!

**Comment by Sanisha003** [comment]
Great job!

**Review by Sanisha003 — APPROVED** [review]
Great job, @eva0marques !

**Comment by eva0marques** [comment]
@kyle-messier yeah, it's hard to progress if we do not compose with the actual state of the library...

**Pull request merged**
